### ISSUE TITLE
URLs in Admin show as HTML rather than clickable links

### ISSUE THREAD

**Issue by philgyford** [easy-as-python/django-webmention#18]
In both the Admin list view and the create/edit view for Webmentions, the clickable links show as HTML rather than clickable links:

![Screenshot 2020-08-24 at 12 42 03](https://user-images.githubusercontent.com/66670/91041156-70cf1300-e607-11ea-8712-4d6b1cc54613.png)

![Screenshot 2020-08-24 at 12 42 32](https://user-images.githubusercontent.com/66670/91041166-74629a00-e607-11ea-9aae-10331b7fcf32.png)

I guess they should be building the HTML using `format_html()`, something like in [this StackOverflow answer](https://stackoverflow.com/a/31745953/250962).

I don't know if the Response body in the create/edit view is supposed to be raw HTML like that - maybe it is; if so, that's fine :)

(Django 3.1)

**Comment by daneah** [comment]
Thanks for the report! I’ll have a look at that.
