### ISSUE TITLE
What else is required to enable webmentions?

### ISSUE THREAD

**Issue by philgyford** [easy-as-python/django-webmention#19]
It would be great to have a little more documentation about what installing this does, and what else is required. I have a very rough idea of how webmentions work, but am very, very far from an expert, so forgive me if any of this is blindingly obvious to you... but I'm a bit stumped as to how to proceed.

1. Having installed django-webmention as described in the README I'm not sure what I should expect to see happen
    1. What exactly does django-webmention do that enables Webmentions to be received or sent?
    2. I noticed that there's an HTTP Response header like `Link: <https://example.org/webmention/receive>; rel="webmention"`. It should be mentioned that this is what happens. Does anything else happen?
    2. What, if anything, do I need to do other than decorate a view?
2. Having created a new page featuring the 23 Discovery Test URLs on [Webmention Rocks!](Webmention Endpoint Discovery) I don't see anything appearing on that site to indicate webmentions have been sent. Should I?
3. Doing the first "Test Your Receiver" test on that site I do receive a webmention and can see it in the admin!
    1. I *guess* I'm supposed to mark an incoming webmention as "Reviewed" if it's OK? What if I "review" a webmention and decide that it's unwanted or spam? Should I delete it?
    2. I *assume* that for any page that has webmentions enabled I should query for any Webmention objects that have a `response_to` attribute that matches the URL of that page, pass them to the template and display them?
4. Should I add something else to my templates to let people know that Webmentions are accepted? If so, what?

Sorry if this is basic but having installed it I was a bit "Now what? Do I have to do anything else? Is it working? How can I tell?"

**Comment by daneah** [comment]
@philgyford I can answer this more thoroughly later on and add documentation for some of the things you suggest, but the TL;DR for one of the major questions is that this package only enables _receipt_ of webmentions and does not send any out at present.

**Comment by philgyford** [comment]
Ohhh. Maybe it should say that in the README :)

**Comment by daneah** [comment]
Indeed—the pains of a hobby project that hasn't largely changed in 2–4 years 😄

**Comment by philgyford** [comment]
That is a feeling I know all too well!

**Comment by daneah** [comment]
Here's a more extensive answer so you you can compare it with my forthcoming documentation pull request 😄 

It would be great to have a little more documentation about what installing this does, and what else is required. I have a very rough idea of how webmentions work, but am very, very far from an expert, so forgive me if any of this is blindingly obvious to you... but I'm a bit stumped as to how to proceed.

> What exactly does django-webmention do that enables Webmentions to be received or sent?

It enabled receipt of webmentions per the [published webmention spec](https://www.w3.org/TR/webmention). Specifically, it seeks to conform to [3.2](https://www.w3.org/TR/webmention/#receiving-webmentions) at present.

> I noticed that there's an HTTP Response header like Link: <https://example.org/webmention/receive>; rel="webmention". It should be mentioned that this is what happens. Does anything else happen?

I'm always a fan of being explicit without duplicating something better documented elsewhere—I'd rather avoid mentioning the header directly, which is a bit of an implementation detail, and instead link to the receiver spec. Specifically, [3.1.2](https://www.w3.org/TR/webmention/#sender-discovers-receiver-webmention-endpoint) describes this process.

> What, if anything, do I need to do other than decorate a view?

The installation instructions are sufficient to get this going, and maybe this question will be better answered collectively by adding more info for the other questions?

> Having created a new page featuring the 23 Discovery Test URLs on [Webmention Rocks!](Webmention Endpoint Discovery) I don't see anything appearing on that site to indicate webmentions have been sent. Should I?

Not implemented, as discussed—will explicitly mention

> I guess I'm supposed to mark an incoming webmention as "Reviewed" if it's OK? What if I "review" a webmention and decide that it's unwanted or spam? Should I delete it?

I'll mention that you will be able to click received webmentions to see what sites are talking about yours, then mark them as reviewed mostly as a "mark as read" feature.

> I assume that for any page that has webmentions enabled I should query for any Webmention objects that have a response_to attribute that matches the URL of that page, pass them to the template and display them?

This is entirely up to you, but I can add that as a usage suggestion.

> Should I add something else to my templates to let people know that Webmentions are accepted? If so, what?

I don't have any suggestions here—I think it would depend heavily on your use case. If you can elaborate a bit here, I'd be happy to discuss further!

**Comment by philgyford** [comment]
Sorry for the radio silence - I was suddenly very busy. Many thanks for the clarifications, both here and in the README.

Despite my efforts, and despite wanting to use them, I find Webmentions a little baffling, so having to work out both how they work *and* how a specific app works – what aspects of Webmentions it does and doesn't handle – was a bit beyond me.
